; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.42 

	TITLE	c:\Documents and Settings\SudaNix\Desktop\docs\research\examples\ch4\ex30\core\kernel\entry.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?kernel_entry@@YAXXZ				; kernel_entry
EXTRN	?exit@@YAXXZ:PROC				; exit
EXTRN	_main:PROC
EXTRN	?init_ctor@@YAXXZ:PROC				; init_ctor
; Function compile flags: /Ogtp
; File c:\documents and settings\sudanix\desktop\docs\research\examples\ch4\ex30\core\kernel\entry.cpp
;	COMDAT ?kernel_entry@@YAXXZ
_TEXT	SEGMENT
?kernel_entry@@YAXXZ PROC				; kernel_entry, COMDAT

; 15   : 
; 16   : #ifdef i386
; 17   : 	_asm {
; 18   : 		cli						

	cli

; 19   : 		
; 20   : 		mov ax, 10h				// select data descriptor in GDT.

	mov	ax, 16					; 00000010H

; 21   : 		mov ds, ax

	mov	ds, ax

; 22   : 		mov es, ax

	mov	es, ax

; 23   : 		mov fs, ax

	mov	fs, ax

; 24   : 		mov gs, ax

	mov	gs, ax

; 25   : 		mov ss, ax				// Set up base stack

	mov	ss, ax

; 26   : 		mov esp, 0x90000

	mov	esp, 589824				; 00090000H

; 27   : 		mov ebp, esp			// store current stack pointer

	mov	ebp, esp

; 28   : 		push ebp

	push	ebp

; 29   : 	}
; 30   : #endif
; 31   : 
; 32   : 	// Execute global constructors
; 33   : 	init_ctor();

	call	?init_ctor@@YAXXZ			; init_ctor

; 34   : 
; 35   : 	// Call kernel entry point
; 36   : 	main();

	call	_main

; 37   : 
; 38   : 	// Cleanup all dynamic dtors
; 39   : 	exit();

	call	?exit@@YAXXZ				; exit

; 40   : 
; 41   : #ifdef i386
; 42   : 	_asm cli

	cli
	npad	4
$LL2@kernel_ent:

; 43   : #endif
; 44   : 
; 45   : 	for(;;);

	jmp	SHORT $LL2@kernel_ent
?kernel_entry@@YAXXZ ENDP				; kernel_entry
_TEXT	ENDS
END
