; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.42 

	TITLE	c:\Documents and Settings\SudaNix\Desktop\docs\research\examples\ch4\software_inetrrupt\core\kernel\main.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG2556	DB	'eqra Operating System (eqraOS) Preparing to load...', 00H
$SG2557	DB	'eqraOS Starting Up...', 00H
	ORG $+2
$SG2558	DB	' Initializing Hardware Abstraction Layer (HAL.lib)... ', 00H
CONST	ENDS
PUBLIC	_main
EXTRN	?hal_init@@YAHXZ:PROC				; hal_init
EXTRN	?kputs@@YAXPAD@Z:PROC				; kputs
EXTRN	?kset_color@@YAII@Z:PROC			; kset_color
EXTRN	?kgoto_xy@@YAXII@Z:PROC				; kgoto_xy
EXTRN	?kclear@@YAXG@Z:PROC				; kclear
; Function compile flags: /Ogtpy
; File c:\documents and settings\sudanix\desktop\docs\research\examples\ch4\software_inetrrupt\core\kernel\main.cpp
_TEXT	SEGMENT
_main	PROC

; 27   : 	kclear(0x18);

	push	24					; 00000018H
	call	?kclear@@YAXG@Z				; kclear

; 28   : 	kgoto_xy(0,0);

	push	0
	push	0
	call	?kgoto_xy@@YAXII@Z			; kgoto_xy

; 29   : 
; 30   : 	kset_color(0x70);

	push	112					; 00000070H
	call	?kset_color@@YAII@Z			; kset_color

; 31   : 	kputs("eqra Operating System (eqraOS) Preparing to load...");

	push	OFFSET $SG2556
	call	?kputs@@YAXPAD@Z			; kputs

; 32   : 
; 33   : 	kgoto_xy(0,1);

	push	1
	push	0
	call	?kgoto_xy@@YAXII@Z			; kgoto_xy

; 34   : 	kset_color(0x19);

	push	25					; 00000019H
	call	?kset_color@@YAII@Z			; kset_color

; 35   : 	kputs("eqraOS Starting Up...");

	push	OFFSET $SG2557
	call	?kputs@@YAXPAD@Z			; kputs

; 36   : 
; 37   : 	kset_color(0x70);

	push	112					; 00000070H
	call	?kset_color@@YAII@Z			; kset_color

; 38   : 	kgoto_xy(0,24);

	push	24					; 00000018H
	push	0
	call	?kgoto_xy@@YAXII@Z			; kgoto_xy

; 39   : 	kputs(" Initializing Hardware Abstraction Layer (HAL.lib)... "); 

	push	OFFSET $SG2558
	call	?kputs@@YAXPAD@Z			; kputs

; 40   : 
; 41   : 	kset_color(0x19);

	push	25					; 00000019H
	call	?kset_color@@YAII@Z			; kset_color

; 42   : 	kgoto_xy(0,2);

	push	2
	push	0
	call	?kgoto_xy@@YAXII@Z			; kgoto_xy
	add	esp, 64					; 00000040H

; 43   : 
; 44   : 	hal_init();

	call	?hal_init@@YAHXZ			; hal_init

; 45   : 
; 46   : 	
; 47   : 	//geninterrupt (0x15);
; 48   : 
; 49   : 	/*kprintf("    eqraOS Kernel executed.\n\n");
; 50   : 
; 51   : 	kprintf("                ___ ___ ________ _  / __ \\ / __/\n");
; 52   : 	kprintf("               / -_) _ `/ __/ _ `/ / /_/ /_\\ \\  \n");
; 53   : 	kprintf("               \\__/\\_, /_/  \\_,_/  \\____//___/  \n");
; 54   : 	kprintf("                    /_/                         \n");
; 55   : 	*/
; 56   : 	
; 57   : 	//gen_interrupt(0x15);
; 58   : 	return 0;

	xor	eax, eax

; 59   : }

	ret	0
_main	ENDP
_TEXT	ENDS
END
