; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.42 

	TITLE	c:\Documents and Settings\SudaNix\Desktop\eqraOS\eqraOS-doc\examples\ch4\vmm\core\kernel\entry.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?kernel_entry@@YAXPAUmultiboot_info@@@Z		; kernel_entry
EXTRN	?exit@@YAXXZ:PROC				; exit
EXTRN	_main:PROC
EXTRN	?init_ctor@@YAXXZ:PROC				; init_ctor
; Function compile flags: /Ogtpy
; File c:\documents and settings\sudanix\desktop\eqraos\eqraos-doc\examples\ch4\vmm\core\kernel\entry.cpp
_TEXT	SEGMENT
_boot_info$ = 8						; size = 4
?kernel_entry@@YAXPAUmultiboot_info@@@Z PROC		; kernel_entry

; 16   : 
; 17   : #ifdef i386
; 18   : 	_asm {
; 19   : 		cli						

	cli

; 20   : 		
; 21   : 		mov ax, 10h				// select data descriptor in GDT.

	mov	ax, 16					; 00000010H

; 22   : 		mov ds, ax

	mov	ds, ax

; 23   : 		mov es, ax

	mov	es, ax

; 24   : 		mov fs, ax

	mov	fs, ax

; 25   : 		mov gs, ax

	mov	gs, ax

; 26   : 	}
; 27   : #endif
; 28   : 
; 29   : 	// Execute global constructors
; 30   : 	init_ctor();

	call	?init_ctor@@YAXXZ			; init_ctor

; 31   : 
; 32   : 	// Call kernel entry point
; 33   : 	main(boot_info);

	mov	eax, DWORD PTR _boot_info$[esp-4]
	push	eax
	call	_main
	add	esp, 4

; 34   : 
; 35   : 	// Cleanup all dynamic dtors
; 36   : 	exit();

	call	?exit@@YAXXZ				; exit

; 40   : 		cli

	cli

; 41   : 		hlt

	hlt
	npad	6

; 37   : 
; 38   : #ifdef i386
; 39   : 	_asm {

$LL2@kernel_ent:

; 42   : 	}
; 43   : #endif
; 44   : 
; 45   : 	for(;;);

	jmp	SHORT $LL2@kernel_ent
?kernel_entry@@YAXPAUmultiboot_info@@@Z ENDP		; kernel_entry
_TEXT	ENDS
END
