; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.42 

	TITLE	c:\Documents and Settings\SudaNix\Desktop\eqraOS\eqraOS-doc\examples\ch4\vmm\core\kernel\panic.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG2585	DB	0aH, 'Sorry, eqraOS has encountered a problem and has bee'
	DB	'n shutdown.', 0aH, 0aH, 00H
	ORG $+2
$SG2586	DB	'*** STOP: %s', 00H
CONST	ENDS
PUBLIC	?kernel_panic@@YAXPBDZZ				; kernel_panic
EXTRN	?kprintf@@YAHPBDZZ:PROC				; kprintf
EXTRN	?kputs@@YAXPAD@Z:PROC				; kputs
EXTRN	?kset_color@@YAII@Z:PROC			; kset_color
EXTRN	?kgoto_xy@@YAXII@Z:PROC				; kgoto_xy
EXTRN	?kclear@@YAXE@Z:PROC				; kclear
EXTRN	?disable_irq@@YAXXZ:PROC			; disable_irq
; Function compile flags: /Ogtpy
; File c:\documents and settings\sudanix\desktop\eqraos\eqraos-doc\examples\ch4\vmm\core\kernel\panic.cpp
_TEXT	SEGMENT
_msg$ = 8						; size = 4
?kernel_panic@@YAXPBDZZ PROC				; kernel_panic

; 6    : 	
; 7    : 	disable_irq();

	call	?disable_irq@@YAXXZ			; disable_irq

; 8    : 	
; 9    : 	va_list args;
; 10   : 	va_start(args,msg);
; 11   : 	/* missing	*/
; 12   : 	va_end(args);
; 13   : 	
; 14   : 	char* panic = "\nSorry, eqraOS has encountered a problem and has been shutdown.\n\n";
; 15   : 	
; 16   : 	kclear(0x1f);

	push	31					; 0000001fH
	call	?kclear@@YAXE@Z				; kclear

; 17   : 	kgoto_xy(0,0);

	push	0
	push	0
	call	?kgoto_xy@@YAXII@Z			; kgoto_xy

; 18   : 	kset_color(0x1f);

	push	31					; 0000001fH
	call	?kset_color@@YAII@Z			; kset_color

; 19   : 	kputs(panic);

	push	OFFSET $SG2585
	call	?kputs@@YAXPAD@Z			; kputs

; 20   : 	kprintf("*** STOP: %s",msg);

	mov	eax, DWORD PTR _msg$[esp+16]
	push	eax
	push	OFFSET $SG2586
	call	?kprintf@@YAHPBDZZ			; kprintf
	add	esp, 28					; 0000001cH
$LL2@kernel_pan:

; 21   : 	
; 22   : 	/* hang	*/
; 23   : 	for (;;) ;

	jmp	SHORT $LL2@kernel_pan
?kernel_panic@@YAXPBDZZ ENDP				; kernel_panic
_TEXT	ENDS
END
