; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.42 

	TITLE	c:\Documents and Settings\SudaNix\Desktop\eqraOS\eqraOS-doc\examples\ch4\keyboard_driver\core\kernel\kdisplay.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?tbuf@@3PADA					; tbuf
PUBLIC	?video_memory@@3PAGA				; video_memory
PUBLIC	?_x_pos@@3EA					; _x_pos
PUBLIC	?_y_pos@@3EA					; _y_pos
PUBLIC	?_color@@3EA					; _color
PUBLIC	?bchars@@3PADA					; bchars
_BSS	SEGMENT
?tbuf@@3PADA DB	020H DUP (?)				; tbuf
?_x_pos@@3EA DB	01H DUP (?)				; _x_pos
	ALIGN	4

?_y_pos@@3EA DB	01H DUP (?)				; _y_pos
	ALIGN	4

?_color@@3EA DB	01H DUP (?)				; _color
_BSS	ENDS
_DATA	SEGMENT
?video_memory@@3PAGA DD 0b8000H				; video_memory
?bchars@@3PADA DB 030H					; bchars
	DB	031H
	DB	032H
	DB	033H
	DB	034H
	DB	035H
	DB	036H
	DB	037H
	DB	038H
	DB	039H
	DB	041H
	DB	042H
	DB	043H
	DB	044H
	DB	045H
	DB	046H
_DATA	ENDS
PUBLIC	?k_update_cursor@@YAXHH@Z			; k_update_cursor
; Function compile flags: /Ogtpy
; File c:\documents and settings\sudanix\desktop\eqraos\eqraos-doc\examples\ch4\keyboard_driver\core\kernel\kdisplay.cpp
_TEXT	SEGMENT
_x$ = 8							; size = 4
_y$ = 12						; size = 4
?k_update_cursor@@YAXHH@Z PROC				; k_update_cursor

; 23   : 
; 24   :     // get location
; 25   :     uint16_t cursorLocation = y * 80 + x;
; 26   : 
; 27   : #if 0
; 28   : 	// send location to vga controller to set cursor
; 29   : 	disable();
; 30   :     outportb(0x3D4, 14);
; 31   :     outportb(0x3D5, cursorLocation >> 8); // Send the high byte.
; 32   :     outportb(0x3D4, 15);
; 33   :     outportb(0x3D5, cursorLocation);      // Send the low byte.
; 34   : 	enable();
; 35   : #endif
; 36   : 
; 37   : }

	ret	0
?k_update_cursor@@YAXHH@Z ENDP				; k_update_cursor
_TEXT	ENDS
PUBLIC	?scroll@@YAXXZ					; scroll
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
?scroll@@YAXXZ PROC					; scroll

; 87   : 	if (_y_pos >= 25) {

	cmp	BYTE PTR ?_y_pos@@3EA, 25		; _y_pos, 00000019H
	jb	SHORT $LN7@scroll

; 88   : 
; 89   : 		uint16_t attribute = _color << 8;

	xor	eax, eax
	mov	ah, BYTE PTR ?_color@@3EA		; _color
	push	esi
	movzx	edx, ax
	xor	eax, eax
	npad	9
$LL6@scroll:

; 90   : 
; 91   : 		//! move current display up one line
; 92   : 		for (int i=0*80; i < 24*80; i++)
; 93   : 			video_memory [i] = video_memory [i+80];

	mov	ecx, DWORD PTR ?video_memory@@3PAGA	; video_memory
	mov	si, WORD PTR [eax+ecx+160]
	mov	WORD PTR [eax+ecx], si
	add	eax, 2
	cmp	eax, 3840				; 00000f00H
	jl	SHORT $LL6@scroll
	mov	ecx, edx
	or	ecx, 32					; 00000020H

; 94   : 
; 95   : 		//! clear the bottom line
; 96   : 		for (int i=24*80; i<25*80; i++)

	mov	eax, 3840				; 00000f00H
	pop	esi
	npad	9
$LL3@scroll:

; 97   : 			video_memory [i] = attribute | ' ';

	mov	edx, DWORD PTR ?video_memory@@3PAGA	; video_memory
	mov	WORD PTR [eax+edx], cx
	add	eax, 2
	cmp	eax, 4000				; 00000fa0H
	jl	SHORT $LL3@scroll

; 98   : 
; 99   : 		_y_pos = 24;

	mov	BYTE PTR ?_y_pos@@3EA, 24		; _y_pos, 00000018H
$LN7@scroll:

; 100  : 	}
; 101  : }

	ret	0
?scroll@@YAXXZ ENDP					; scroll
_TEXT	ENDS
PUBLIC	?itoa@@YAXIIPAD@Z				; itoa
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_i$ = 8							; size = 4
_base$ = 12						; size = 4
_buf$ = 16						; size = 4
?itoa@@YAXIIPAD@Z PROC					; itoa

; 107  :    int pos = 0;
; 108  :    int opos = 0;
; 109  :    int top = 0;
; 110  : 
; 111  :    if (i == 0 || base > 16) {

	mov	eax, DWORD PTR _i$[esp-4]
	xor	ecx, ecx
	test	eax, eax
	push	esi
	je	SHORT $LN6@itoa
	mov	esi, DWORD PTR _base$[esp]
	cmp	esi, 16					; 00000010H
	ja	SHORT $LN6@itoa
$LL5@itoa:

; 114  :       return;
; 115  :    }
; 116  : 
; 117  :    while (i != 0) {
; 118  :       tbuf[pos] = bchars[i % base];

	xor	edx, edx
	div	esi

; 119  :       pos++;

	add	ecx, 1
	test	eax, eax
	mov	dl, BYTE PTR ?bchars@@3PADA[edx]
	mov	BYTE PTR ?tbuf@@3PADA[ecx-1], dl
	jne	SHORT $LL5@itoa

; 120  :       i /= base;
; 121  :    }
; 122  :    top=pos--;

	mov	esi, ecx
	sub	ecx, 1

; 123  :    for (opos=0; opos<top; pos--,opos++) {

	test	esi, esi
	push	edi
	mov	edi, DWORD PTR _buf$[esp+4]
	jle	SHORT $LN1@itoa

; 120  :       i /= base;
; 121  :    }
; 122  :    top=pos--;

	lea	ecx, DWORD PTR ?tbuf@@3PADA[ecx]
	npad	1
$LL3@itoa:

; 124  :       buf[opos] = tbuf[pos];

	mov	dl, BYTE PTR [ecx]
	mov	BYTE PTR [eax+edi], dl
	add	eax, 1
	sub	ecx, 1
	cmp	eax, esi
	jl	SHORT $LL3@itoa
$LN1@itoa:

; 125  :    }
; 126  :    buf[opos] = 0;

	mov	BYTE PTR [eax+edi], 0
	pop	edi
	pop	esi

; 127  : }

	ret	0
$LN6@itoa:

; 112  :       buf[0] = '0';

	mov	eax, DWORD PTR _buf$[esp]
	mov	BYTE PTR [eax], 48			; 00000030H

; 113  :       buf[1] = '\0';

	mov	BYTE PTR [eax+1], cl
	pop	esi

; 127  : }

	ret	0
?itoa@@YAXIIPAD@Z ENDP					; itoa
_TEXT	ENDS
PUBLIC	?itoa_s@@YAXHIPAD@Z				; itoa_s
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_i$ = 8							; size = 4
_base$ = 12						; size = 4
_buf$ = 16						; size = 4
?itoa_s@@YAXHIPAD@Z PROC				; itoa_s

; 130  :    if (base > 16) return;

	mov	edx, DWORD PTR _base$[esp-4]
	cmp	edx, 16					; 00000010H
	ja	SHORT $LN3@itoa_s

; 131  :    if (i < 0) {

	mov	eax, DWORD PTR _i$[esp-4]
	test	eax, eax

; 132  :       *buf++ = '-';

	mov	ecx, DWORD PTR _buf$[esp-4]
	jge	SHORT $LN1@itoa_s
	mov	BYTE PTR [ecx], 45			; 0000002dH
	add	ecx, 1

; 133  :       i *= -1;

	neg	eax
$LN1@itoa_s:

; 134  :    }
; 135  :    itoa(i,base,buf);

	mov	DWORD PTR _buf$[esp-4], ecx
	mov	DWORD PTR _base$[esp-4], edx
	mov	DWORD PTR _i$[esp-4], eax
	jmp	?itoa@@YAXIIPAD@Z			; itoa
$LN3@itoa_s:

; 136  : }

	ret	0
?itoa_s@@YAXHIPAD@Z ENDP				; itoa_s
_TEXT	ENDS
PUBLIC	?kget_xy@@YAXPAI0@Z				; kget_xy
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_x$ = 8							; size = 4
_y$ = 12						; size = 4
?kget_xy@@YAXPAI0@Z PROC				; kget_xy

; 143  : 	if (x==0 || y==0)

	mov	ecx, DWORD PTR _x$[esp-4]
	test	ecx, ecx
	je	SHORT $LN1@kget_xy
	mov	eax, DWORD PTR _y$[esp-4]
	test	eax, eax
	je	SHORT $LN1@kget_xy

; 144  : 		return;
; 145  : 
; 146  : 	*x = _x_pos;

	movzx	edx, BYTE PTR ?_x_pos@@3EA		; _x_pos
	mov	DWORD PTR [ecx], edx

; 147  : 	*y = _y_pos;

	movzx	ecx, BYTE PTR ?_y_pos@@3EA		; _y_pos
	mov	DWORD PTR [eax], ecx
$LN1@kget_xy:

; 148  : }

	ret	0
?kget_xy@@YAXPAI0@Z ENDP				; kget_xy
_TEXT	ENDS
PUBLIC	?kget_horz@@YAHXZ				; kget_horz
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
?kget_horz@@YAHXZ PROC					; kget_horz

; 151  : 	return 80;

	mov	eax, 80					; 00000050H

; 152  : }

	ret	0
?kget_horz@@YAHXZ ENDP					; kget_horz
_TEXT	ENDS
PUBLIC	?kget_vert@@YAHXZ				; kget_vert
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
?kget_vert@@YAHXZ PROC					; kget_vert

; 155  : 	return 24;

	mov	eax, 24					; 00000018H

; 156  : }

	ret	0
?kget_vert@@YAHXZ ENDP					; kget_vert
_TEXT	ENDS
PUBLIC	?kset_color@@YAII@Z				; kset_color
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_c$ = 8							; size = 4
?kset_color@@YAII@Z PROC				; kset_color

; 182  : 	unsigned old_color = _color;
; 183  : 	_color = c;

	mov	cl, BYTE PTR _c$[esp-4]
	movzx	eax, BYTE PTR ?_color@@3EA		; _color
	mov	BYTE PTR ?_color@@3EA, cl		; _color

; 184  : 	return old_color;
; 185  : }

	ret	0
?kset_color@@YAII@Z ENDP				; kset_color
_TEXT	ENDS
PUBLIC	?kgoto_xy@@YAXII@Z				; kgoto_xy
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_x$ = 8							; size = 4
_y$ = 12						; size = 4
?kgoto_xy@@YAXII@Z PROC					; kgoto_xy

; 189  : 	if (_x_pos <= 80)

	cmp	BYTE PTR ?_x_pos@@3EA, 80		; _x_pos, 00000050H
	ja	SHORT $LN2@kgoto_xy

; 190  : 	    _x_pos = x;

	mov	al, BYTE PTR _x$[esp-4]
	mov	BYTE PTR ?_x_pos@@3EA, al		; _x_pos
$LN2@kgoto_xy:

; 191  : 
; 192  : 	if (_y_pos <= 25)

	cmp	BYTE PTR ?_y_pos@@3EA, 25		; _y_pos, 00000019H
	ja	SHORT $LN1@kgoto_xy

; 193  : 	    _y_pos = y;

	mov	cl, BYTE PTR _y$[esp-4]
	mov	BYTE PTR ?_y_pos@@3EA, cl		; _y_pos
$LN1@kgoto_xy:

; 194  : 
; 195  : 	//! update hardware cursor to new position
; 196  : 	k_update_cursor(_x_pos, _y_pos);
; 197  : }

	ret	0
?kgoto_xy@@YAXII@Z ENDP					; kgoto_xy
_TEXT	ENDS
PUBLIC	?kputc@@YAXE@Z					; kputc
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_c$ = 8							; size = 1
?kputc@@YAXE@Z PROC					; kputc

; 41   : 
; 42   :     uint16_t attribute = _color << 8;

	xor	eax, eax
	mov	ah, BYTE PTR ?_color@@3EA		; _color
	movzx	ecx, ax

; 43   : 
; 44   :     //! backspace character
; 45   :     if (c == 0x08 && _x_pos)

	mov	al, BYTE PTR _c$[esp-4]
	cmp	al, 8
	jne	SHORT $LN11@kputc
	mov	al, BYTE PTR ?_x_pos@@3EA		; _x_pos
	test	al, al
	je	SHORT $LN3@kputc

; 46   :         _x_pos--;

	add	al, 255					; 000000ffH
	mov	BYTE PTR ?_x_pos@@3EA, al		; _x_pos
	jmp	SHORT $LN3@kputc
$LN11@kputc:

; 47   : 
; 48   :     //! tab character
; 49   :     else if (c == 0x09)

	cmp	al, 9
	jne	SHORT $LN9@kputc

; 50   :         _x_pos = (_x_pos+8) & ~(8-1);

	mov	al, BYTE PTR ?_x_pos@@3EA		; _x_pos
	add	al, 8
	and	al, 248					; 000000f8H
	mov	BYTE PTR ?_x_pos@@3EA, al		; _x_pos
	jmp	SHORT $LN3@kputc
$LN9@kputc:

; 51   : 
; 52   :     //! carriage return
; 53   :     else if (c == '\r')

	cmp	al, 13					; 0000000dH

; 54   :         _x_pos = 0;

	je	SHORT $LN19@kputc

; 55   : 
; 56   :     //! new line
; 57   : 	else if (c == '\n') {

	cmp	al, 10					; 0000000aH

; 58   :         _x_pos = 0;
; 59   :         _y_pos++;

	je	SHORT $LN20@kputc

; 60   : 	}
; 61   : 
; 62   :     //! printable characters
; 63   :     else if(c >= ' ') {

	cmp	al, 32					; 00000020H
	jb	SHORT $LN16@kputc

; 64   : 
; 65   : 		//! display character on screen
; 66   :         uint16_t* location = video_memory + (_y_pos*80 + _x_pos);
; 67   :         *location = c | attribute;

	movzx	dx, al
	movzx	eax, BYTE PTR ?_y_pos@@3EA		; _y_pos
	or	dx, cx
	movzx	ecx, BYTE PTR ?_x_pos@@3EA		; _x_pos
	lea	eax, DWORD PTR [eax+eax*4]
	shl	eax, 4
	add	eax, ecx
	mov	ecx, DWORD PTR ?video_memory@@3PAGA	; video_memory
	mov	WORD PTR [ecx+eax*2], dx

; 68   :         _x_pos++;

	mov	al, BYTE PTR ?_x_pos@@3EA		; _x_pos
	add	al, 1
	mov	BYTE PTR ?_x_pos@@3EA, al		; _x_pos
	jmp	SHORT $LN3@kputc
$LN16@kputc:
	mov	al, BYTE PTR ?_x_pos@@3EA		; _x_pos
$LN3@kputc:

; 69   :     }
; 70   : 
; 71   :     //! if we are at edge of row, go to new line
; 72   :     if (_x_pos >= 80) {

	cmp	al, 80					; 00000050H
	jb	SHORT $LN2@kputc
$LN20@kputc:

; 75   :         _y_pos++;

	add	BYTE PTR ?_y_pos@@3EA, 1		; _y_pos
$LN19@kputc:

; 73   : 
; 74   :         _x_pos = 0;

	mov	BYTE PTR ?_x_pos@@3EA, 0		; _x_pos
$LN2@kputc:

; 76   :     }
; 77   : 
; 78   : 	//! if we are at the last line, scroll up
; 79   : 	if (_y_pos >= 25)

	cmp	BYTE PTR ?_y_pos@@3EA, 25		; _y_pos, 00000019H
	jb	SHORT $LN1@kputc

; 80   : 		scroll ();

	jmp	?scroll@@YAXXZ				; scroll
$LN1@kputc:

; 81   : 
; 82   :     //! update hardware cursor
; 83   : 	k_update_cursor (_x_pos,_y_pos);
; 84   : }

	ret	0
?kputc@@YAXE@Z ENDP					; kputc
_TEXT	ENDS
PUBLIC	?kclear@@YAXE@Z					; kclear
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_c$ = 8							; size = 1
?kclear@@YAXE@Z PROC					; kclear

; 161  : 	//! clear video memory by writing space characters to it
; 162  : 	for (int i = 0; i < 80*25; i++)

	xor	ecx, ecx
	mov	ch, BYTE PTR _c$[esp-4]
	xor	edx, edx
	push	esi
	or	ecx, 32					; 00000020H
	xor	eax, eax
	npad	2
$LL3@kclear:

; 163  :         video_memory[i] = ' ' | (c << 8);

	mov	esi, DWORD PTR ?video_memory@@3PAGA	; video_memory
	mov	WORD PTR [eax+esi], cx
	add	eax, 2
	cmp	eax, 4000				; 00000fa0H
	jl	SHORT $LL3@kclear

; 164  : 
; 165  :     //! move position back to start
; 166  :     kgoto_xy (0,0);

	cmp	BYTE PTR ?_x_pos@@3EA, 80		; _x_pos, 00000050H
	pop	esi
	ja	SHORT $LN7@kclear
	mov	BYTE PTR ?_x_pos@@3EA, dl		; _x_pos
$LN7@kclear:
	cmp	BYTE PTR ?_y_pos@@3EA, 25		; _y_pos, 00000019H
	ja	SHORT $LN6@kclear
	mov	BYTE PTR ?_y_pos@@3EA, dl		; _y_pos
$LN6@kclear:

; 167  : }

	ret	0
?kclear@@YAXE@Z ENDP					; kclear
_TEXT	ENDS
PUBLIC	?kputs@@YAXPAD@Z				; kputs
EXTRN	?strlen@@YAIPBD@Z:PROC				; strlen
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_str$ = 8						; size = 4
?kputs@@YAXPAD@Z PROC					; kputs

; 171  : {

	push	edi

; 172  : 	if (!str)

	mov	edi, DWORD PTR _str$[esp]
	test	edi, edi
	je	SHORT $LN1@kputs
	push	esi

; 173  : 		return;
; 174  : 		
; 175  : 	for (unsigned int i=0;i<strlen(str);++i)

	push	edi
	xor	esi, esi
	call	?strlen@@YAIPBD@Z			; strlen
	add	esp, 4
	test	eax, eax
	jbe	SHORT $LN9@kputs
	npad	7
$LL3@kputs:

; 176  : 		kputc(str[i]);

	movzx	eax, BYTE PTR [esi+edi]
	push	eax
	call	?kputc@@YAXE@Z				; kputc
	push	edi
	add	esi, 1
	call	?strlen@@YAIPBD@Z			; strlen
	add	esp, 8
	cmp	esi, eax
	jb	SHORT $LL3@kputs
$LN9@kputs:
	pop	esi
$LN1@kputs:
	pop	edi

; 177  : }

	ret	0
?kputs@@YAXPAD@Z ENDP					; kputs
_TEXT	ENDS
PUBLIC	?kprintf@@YAHPBDZZ				; kprintf
EXTRN	?strcpy@@YAPADPADPBD@Z:PROC			; strcpy
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_str$2741 = -64						; size = 32
_str$2731 = -64						; size = 32
_str$2720 = -64						; size = 64
_str$ = 8						; size = 4
?kprintf@@YAHPBDZZ PROC					; kprintf

; 200  : int kprintf(const char* str, ...) {

	sub	esp, 64					; 00000040H
	push	ebx
	push	ebp

; 201  : 
; 202  : 	if(!str)

	mov	ebp, DWORD PTR _str$[esp+68]
	xor	ebx, ebx
	cmp	ebp, ebx
	jne	SHORT $LN15@kprintf
	pop	ebp

; 203  : 		return 0;

	xor	eax, eax
	pop	ebx

; 274  : }

	add	esp, 64					; 00000040H
	ret	0
$LN15@kprintf:
	push	esi
	push	edi

; 207  : 	
; 208  : 	size_t i=0;
; 209  : 
; 210  : 	for (; i<strlen(str);i++) {

	push	ebp
	xor	edi, edi
	call	?strlen@@YAIPBD@Z			; strlen
	add	esp, 4
	test	eax, eax
	jbe	$LN12@kprintf

; 204  : 
; 205  : 	va_list		args;
; 206  : 	va_start (args, str);

	lea	esi, DWORD PTR _str$[esp+76]
$LL14@kprintf:

; 211  : 
; 212  : 		switch (str[i]) {

	movzx	eax, BYTE PTR [edi+ebp]
	cmp	al, 37					; 00000025H
	je	SHORT $LN9@kprintf

; 261  : 				}
; 262  : 
; 263  : 				break;
; 264  : 
; 265  : 			default:
; 266  : 				kputc (str[i]);

	push	eax
	call	?kputc@@YAXE@Z				; kputc
	add	esp, 4

; 267  : 				break;

	jmp	$LN13@kprintf
$LN9@kprintf:

; 213  : 
; 214  : 			case '%':
; 215  : 
; 216  : 				switch (str[i+1]) {

	movsx	eax, BYTE PTR [edi+ebp+1]
	add	eax, -88				; ffffffa8H
	cmp	eax, 32					; 00000020H
	ja	$LN2@kprintf
	movzx	eax, BYTE PTR $LN28@kprintf[eax]
	jmp	DWORD PTR $LN33@kprintf[eax*4]
$LN6@kprintf:

; 217  : 
; 218  : 					/*** characters ***/
; 219  : 					case 'c': {
; 220  : 						char c = va_arg (args, char);
; 221  : 						kputc (c);

	movzx	ecx, BYTE PTR [esi+4]
	add	esi, 4
	push	ecx
	call	?kputc@@YAXE@Z				; kputc
	add	esp, 4

; 222  : 						i++;		// go to next character
; 223  : 						break;

	jmp	$LN31@kprintf
$LN5@kprintf:

; 224  : 					}
; 225  : 
; 226  : 					/*** address of ***/
; 227  : 					case 's': {
; 228  : 						int c = (int&) va_arg (args, char);
; 229  : 						char str[64];
; 230  : 						strcpy (str,(const char*)c);

	mov	edx, DWORD PTR [esi+4]
	add	esi, 4
	push	edx
	lea	eax, DWORD PTR _str$2720[esp+84]
	push	eax
	call	?strcpy@@YAPADPADPBD@Z			; strcpy

; 231  : 						kputs (str);

	lea	ecx, DWORD PTR _str$2720[esp+88]
	push	ecx
	call	?kputs@@YAXPAD@Z			; kputs
	add	esp, 12					; 0000000cH

; 232  : 						i++;		// go to next character
; 233  : 						break;

	jmp	$LN31@kprintf
$LN4@kprintf:

; 234  : 					}
; 235  : 
; 236  : 					/*** integers ***/
; 237  : 					case 'd':
; 238  : 					case 'i': {
; 239  : 						int c = va_arg (args, int);
; 240  : 						char str[32]={0};

	xor	eax, eax
	add	esi, 4
	mov	DWORD PTR _str$2731[esp+81], eax
	mov	DWORD PTR _str$2731[esp+85], eax
	mov	DWORD PTR _str$2731[esp+89], eax
	mov	DWORD PTR _str$2731[esp+93], eax
	mov	DWORD PTR _str$2731[esp+97], eax
	mov	DWORD PTR _str$2731[esp+101], eax
	mov	DWORD PTR _str$2731[esp+105], eax
	mov	WORD PTR _str$2731[esp+109], ax
	mov	BYTE PTR _str$2731[esp+111], al

; 241  : 						itoa_s (c, 10, str);

	mov	eax, DWORD PTR [esi]
	cmp	eax, ebx
	mov	BYTE PTR _str$2731[esp+80], bl
	lea	ecx, DWORD PTR _str$2731[esp+80]
	jge	SHORT $LN18@kprintf
	mov	BYTE PTR _str$2731[esp+80], 45		; 0000002dH
	lea	ecx, DWORD PTR _str$2731[esp+81]
	neg	eax
$LN18@kprintf:
	push	ecx
	push	10					; 0000000aH
	push	eax
	call	?itoa@@YAXIIPAD@Z			; itoa

; 242  : 						kputs (str);

	lea	edx, DWORD PTR _str$2731[esp+92]
	push	edx

; 243  : 						i++;		// go to next character
; 244  : 						break;

	jmp	SHORT $LN32@kprintf
$LN3@kprintf:

; 245  : 					}
; 246  : 
; 247  : 					/*** display in hex ***/
; 248  : 					case 'X':
; 249  : 					case 'x': {
; 250  : 						int c = va_arg (args, int);
; 251  : 						char str[32]={0};

	xor	eax, eax
	add	esi, 4
	mov	DWORD PTR _str$2741[esp+81], eax
	mov	DWORD PTR _str$2741[esp+85], eax
	mov	DWORD PTR _str$2741[esp+89], eax
	mov	DWORD PTR _str$2741[esp+93], eax
	mov	DWORD PTR _str$2741[esp+97], eax
	mov	DWORD PTR _str$2741[esp+101], eax
	mov	DWORD PTR _str$2741[esp+105], eax
	mov	WORD PTR _str$2741[esp+109], ax
	mov	BYTE PTR _str$2741[esp+111], al

; 252  : 						itoa_s (c,16,str);

	mov	eax, DWORD PTR [esi]
	cmp	eax, ebx
	mov	BYTE PTR _str$2741[esp+80], bl
	lea	ecx, DWORD PTR _str$2741[esp+80]
	jge	SHORT $LN22@kprintf
	mov	BYTE PTR _str$2741[esp+80], 45		; 0000002dH
	lea	ecx, DWORD PTR _str$2741[esp+81]
	neg	eax
$LN22@kprintf:
	push	ecx
	push	16					; 00000010H
	push	eax
	call	?itoa@@YAXIIPAD@Z			; itoa

; 253  : 						kputs (str);

	lea	eax, DWORD PTR _str$2741[esp+92]
	push	eax
$LN32@kprintf:
	call	?kputs@@YAXPAD@Z			; kputs
	add	esp, 16					; 00000010H
$LN31@kprintf:

; 254  : 						i++;		// go to next character

	add	edi, 1
$LN13@kprintf:

; 207  : 	
; 208  : 	size_t i=0;
; 209  : 
; 210  : 	for (; i<strlen(str);i++) {

	push	ebp
	add	edi, 1
	call	?strlen@@YAIPBD@Z			; strlen
	add	esp, 4
	cmp	edi, eax
	jb	$LL14@kprintf
$LN12@kprintf:

; 268  : 		}
; 269  : 
; 270  : 	}
; 271  : 
; 272  : 	va_end (args);
; 273  : 	return i;

	mov	eax, edi
	pop	edi
	pop	esi
	pop	ebp
	pop	ebx

; 274  : }

	add	esp, 64					; 00000040H
	ret	0
$LN2@kprintf:
	pop	edi
	pop	esi
	pop	ebp

; 255  : 						break;
; 256  : 					}
; 257  : 
; 258  : 					default:
; 259  : 						va_end (args);
; 260  : 						return 1;

	mov	eax, 1
	pop	ebx

; 274  : }

	add	esp, 64					; 00000040H
	ret	0
	npad	1
$LN33@kprintf:
	DD	$LN3@kprintf
	DD	$LN6@kprintf
	DD	$LN4@kprintf
	DD	$LN5@kprintf
	DD	$LN2@kprintf
$LN28@kprintf:
	DB	0
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	1
	DB	2
	DB	4
	DB	4
	DB	4
	DB	4
	DB	2
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	4
	DB	3
	DB	4
	DB	4
	DB	4
	DB	4
	DB	0
?kprintf@@YAHPBDZZ ENDP					; kprintf
_TEXT	ENDS
END
