; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.42 

	TITLE	c:\Documents and Settings\SudaNix\Desktop\eqraOS\eqraOS-doc\examples\ch4\keyboard_driver\core\kernel\vmm_pde.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?pde_add_attrib@@YAXPAII@Z			; pde_add_attrib
; Function compile flags: /Ogtpy
; File c:\documents and settings\sudanix\desktop\eqraos\eqraos-doc\examples\ch4\keyboard_driver\core\kernel\vmm_pde.cpp
_TEXT	SEGMENT
_e$ = 8							; size = 4
_attrib$ = 12						; size = 4
?pde_add_attrib@@YAXPAII@Z PROC				; pde_add_attrib

; 6    : 	*e = *e | attrib; 

	mov	eax, DWORD PTR _e$[esp-4]
	mov	ecx, DWORD PTR _attrib$[esp-4]
	or	DWORD PTR [eax], ecx

; 7    : }

	ret	0
?pde_add_attrib@@YAXPAII@Z ENDP				; pde_add_attrib
_TEXT	ENDS
PUBLIC	?pde_del_attrib@@YAXPAII@Z			; pde_del_attrib
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_e$ = 8							; size = 4
_attrib$ = 12						; size = 4
?pde_del_attrib@@YAXPAII@Z PROC				; pde_del_attrib

; 10   : 	*e = *e & ~attrib;

	mov	ecx, DWORD PTR _attrib$[esp-4]
	mov	eax, DWORD PTR _e$[esp-4]
	not	ecx
	and	DWORD PTR [eax], ecx

; 11   : }

	ret	0
?pde_del_attrib@@YAXPAII@Z ENDP				; pde_del_attrib
_TEXT	ENDS
PUBLIC	?pde_set_frame@@YAXPAII@Z			; pde_set_frame
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_e$ = 8							; size = 4
_addr$ = 12						; size = 4
?pde_set_frame@@YAXPAII@Z PROC				; pde_set_frame

; 14   : 	*e = ( *e & ~I386_PDE_FRAME ) | addr ;

	mov	eax, DWORD PTR _e$[esp-4]
	mov	ecx, DWORD PTR [eax]
	and	ecx, -2147479553			; 80000fffH
	or	ecx, DWORD PTR _addr$[esp-4]
	mov	DWORD PTR [eax], ecx

; 15   : }

	ret	0
?pde_set_frame@@YAXPAII@Z ENDP				; pde_set_frame
_TEXT	ENDS
PUBLIC	?pde_get_frame@@YAII@Z				; pde_get_frame
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_e$ = 8							; size = 4
?pde_get_frame@@YAII@Z PROC				; pde_get_frame

; 18   : 	return e & I386_PDE_FRAME ;

	mov	eax, DWORD PTR _e$[esp-4]
	and	eax, 2147479552				; 7ffff000H

; 19   : }

	ret	0
?pde_get_frame@@YAII@Z ENDP				; pde_get_frame
_TEXT	ENDS
PUBLIC	?pde_is_present@@YA_NI@Z			; pde_is_present
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_e$ = 8							; size = 4
?pde_is_present@@YA_NI@Z PROC				; pde_is_present

; 22   : 	return e & I386_PDE_PRESENT;

	mov	eax, DWORD PTR _e$[esp-4]
	and	eax, 1

; 23   : }

	ret	0
?pde_is_present@@YA_NI@Z ENDP				; pde_is_present
_TEXT	ENDS
PUBLIC	?pde_is_writable@@YA_NI@Z			; pde_is_writable
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_e$ = 8							; size = 4
?pde_is_writable@@YA_NI@Z PROC				; pde_is_writable

; 26   : 	return e & I386_PDE_WRITABLE ;

	mov	eax, DWORD PTR _e$[esp-4]
	shr	eax, 1
	and	al, 1

; 27   : }

	ret	0
?pde_is_writable@@YA_NI@Z ENDP				; pde_is_writable
_TEXT	ENDS
PUBLIC	?pde_is_user@@YA_NI@Z				; pde_is_user
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_e$ = 8							; size = 4
?pde_is_user@@YA_NI@Z PROC				; pde_is_user

; 30   : 	return e & I386_PDE_USER;

	mov	eax, DWORD PTR _e$[esp-4]
	shr	eax, 2
	and	al, 1

; 31   : }

	ret	0
?pde_is_user@@YA_NI@Z ENDP				; pde_is_user
_TEXT	ENDS
PUBLIC	?pde_is_4mb@@YA_NI@Z				; pde_is_4mb
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_e$ = 8							; size = 4
?pde_is_4mb@@YA_NI@Z PROC				; pde_is_4mb

; 34   : 	return e & I386_PDE_4MB;

	mov	eax, DWORD PTR _e$[esp-4]
	shr	eax, 7
	and	al, 1

; 35   : }

	ret	0
?pde_is_4mb@@YA_NI@Z ENDP				; pde_is_4mb
_TEXT	ENDS
PUBLIC	?pde_enable_global@@YAXI@Z			; pde_enable_global
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_e$ = 8							; size = 4
?pde_enable_global@@YAXI@Z PROC				; pde_enable_global

; 38   : 
; 39   : }

	ret	0
?pde_enable_global@@YAXI@Z ENDP				; pde_enable_global
_TEXT	ENDS
END
